//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeleCom.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Порты
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Порты()
        {
            this.ПортыВоборудовании = new HashSet<ПортыВоборудовании>();
        }
    
        public int ID_порт { get; set; }
        public string Наименование_типа { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ПортыВоборудовании> ПортыВоборудовании { get; set; }
    }
}
